### ISSUE TITLE
Player Dimension

### ISSUE THREAD

**Issue by josh-spratt** [josh-spratt/play-by-play-model#3]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
We should build a player dimension containing player metadata. It will be a great starting point for building this play by play model.

**Describe alternatives you've considered**
No good alternatives. We could just jam all the player attributes into on hyperdenormalized table.

**Additional context**
@JJohnson-DA already did the work to pull the player data into a table.

* We'll need to find column definitions for all that data and add it to its own dbt schema .yml file.
* We'll need to parse the columns we care about and build a dbt model for the player dimension

**Comment by JJohnson-DA** [comment]
In the future we may want to make the `player_dim` a SCD
